[package]
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
description = "A fresh FRAME-based Substrate runtime, ready for hacking."
edition = "2021"
homepage = "https://substrate.io/"
license = "Unlicense"
name = "aurora-testnet-runtime"
publish = false
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}

# Frontier
fp-rpc = {default-features = false, git = "https://github.com/cryptoviet/frontier", branch = "v1.0.0-dev"}
fp-self-contained = {default-features = false, git = "https://github.com/cryptoviet/frontier", branch = "v1.0.0-dev"}
pallet-base-fee = {default-features = false, git = "https://github.com/cryptoviet/frontier", branch = "v1.0.0-dev"}
pallet-dynamic-fee = {default-features = false, git = "https://github.com/cryptoviet/frontier", branch = "v1.0.0-dev"}
pallet-ethereum = {default-features = false, git = "https://github.com/cryptoviet/frontier", branch = "v1.0.0-dev"}
pallet-evm = {default-features = false, git = "https://github.com/cryptoviet/frontier", branch = "v1.0.0-dev"}
pallet-evm-precompile-modexp = {default-features = false, git = "https://github.com/cryptoviet/frontier", branch = "v1.0.0-dev"}
pallet-evm-precompile-sha3fips = {default-features = false, git = "https://github.com/cryptoviet/frontier", branch = "v1.0.0-dev"}
pallet-evm-precompile-simple = {default-features = false, git = "https://github.com/cryptoviet/frontier", branch = "v1.0.0-dev"}

# Substrate
frame-executive = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
frame-support = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
frame-system = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
pallet-aura = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
pallet-balances = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
pallet-grandpa = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
pallet-randomness-collective-flip = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
pallet-sudo = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
pallet-timestamp = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
pallet-transaction-payment = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-api = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-block-builder = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-consensus-aura = {version = "0.10.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-core = {version = "5.0.0", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-inherents = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-offchain = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-runtime = {version = "5.0.0", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-session = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-std = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-transaction-pool = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-version = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}

# Used for the node template's RPCs
frame-system-rpc-runtime-api = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
pallet-transaction-payment-rpc-runtime-api = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}

# Used for runtime benchmarking
frame-benchmarking = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot", optional = true}
frame-system-benchmarking = {version = "4.0.0-dev", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot", optional = true}
hex-literal = {version = "0.3.4", optional = true}

# Local Dependencies
pallet-player = {version = "4.0.0-dev", default-features = false, path = "../pallets/player"}
pallet-pool = {version = "4.0.0-dev", default-features = false, path = "../pallets/pool"}
pallet-template = {version = "4.0.0-dev", default-features = false, path = "../pallets/template"}
pallet-tx-handler = {version = "4.0.0-dev", default-features = false, path = "../pallets/tx-handler"}

# unit test
[dev.dependencies]
sp-io = {version = "5.0.0", default-features = false, git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}

[build-dependencies]
substrate-wasm-builder = {version = "5.0.0-dev", git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}

[features]
aura = []
default = ["std", "aura"]
manual-seal = []
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system-benchmarking",
  "frame-system/runtime-benchmarks",
  "hex-literal",
  "pallet-balances/runtime-benchmarks",
  "pallet-template/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "pallet-ethereum/runtime-benchmarks",
  "pallet-pool/runtime-benchmarks",
]
std = [
  "codec/std",
  "scale-info/std",
  "frame-executive/std",
  "frame-support/std",
  "frame-system-rpc-runtime-api/std",
  "frame-system/std",
  "pallet-aura/std",
  "pallet-balances/std",
  "pallet-grandpa/std",
  "pallet-randomness-collective-flip/std",
  "pallet-sudo/std",
  "pallet-template/std",
  "pallet-timestamp/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "pallet-transaction-payment/std",
  "sp-api/std",
  "sp-block-builder/std",
  "sp-consensus-aura/std",
  "sp-core/std",
  "sp-inherents/std",
  "sp-offchain/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-std/std",
  "sp-transaction-pool/std",
  "sp-version/std",
  'pallet-evm/std',
  'pallet-ethereum/std',
  'fp-self-contained/std',
  'fp-rpc/std',
  'pallet-base-fee/std',
  "pallet-dynamic-fee/std",
  "pallet-evm-precompile-simple/std",
  "pallet-evm-precompile-sha3fips/std",
  "pallet-pool/std",
]
